name: Build Codev App APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools
          pip install buildozer

      - name: Set up Java (OpenJDK 11)
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Buildozer Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-11-jdk \
            zlib1g-dev libncurses5 \
            libstdc++6 libffi-dev \
            libssl-dev python3-pip \
            python3-setuptools git

      - name: Initialize Buildozer Spec (if not exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: codev-debug-apk
          path: bin/*.apk
