name: Build Codev App APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install buildozer

      - name: Set up Java (OpenJDK 11)
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install buildozer Android dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk zlib1g-dev python3-pip python3-setuptools git libncurses5 libstdc++6 libffi-dev libssl-dev

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: codev-debug-apk
          path: bin/*.apk
